theme: jekyll-theme-minimal
title: "Kade Engine Community"
description: "KEC is a fork of Kade Engine that aims to fix most of its issues."
show_downloads: true
replace_index_with: "https://cors-thing.puyo.workers.dev/master/"
logo: "https://raw.githubusercontent.com/TheRealJake12/Kade-Engine-Community/master/assets/preload/images/KadeEngineLogoOld.png"
url: "https://therealjake12.github.io/Kade-Engine-Community/"
